(()=>{const{clean,number,vin,mileage,year}=window.CarBucketNormalize;
const PRICE_GOOD=/your price|our price|sale price|selling price|internet price|online price|cash price|everyone'?s price|asking price|list price|price/i;
const PRICE_BAD=/msrp|sticker|payment|monthly|per month|apr|rebate|incentive|fee|tax|down payment|market|below market|savings/i;
const MAKES=new Set(['acura','alfa romeo','aston martin','audi','bentley','bmw','buick','cadillac','chevrolet','chevy','chrysler','dodge','ferrari','fiat','ford','genesis','gmc','honda','hyundai','infiniti','jaguar','jeep','kia','lamborghini','land rover','lexus','lincoln','lotus','lucid','maserati','mazda','mclaren','mercedes-benz','mercedes','mini','mitsubishi','nissan','polestar','pontiac','porsche','ram','rivian','rolls-royce','saab','saturn','scion','smart','subaru','suzuki','tesla','toyota','volkswagen','vw','volvo']);
const lines=()=>[...(document.body?.innerText||'').split(/\r?\n/)].map(clean).filter(Boolean);
function labeled(names){const ls=lines(),wanted=names.map(x=>x.toLowerCase());for(let i=0;i<ls.length;i++){const t=ls[i].toLowerCase();for(const label of wanted){if(t===label||t.startsWith(label+':')||t.startsWith(label+' -')||t.startsWith(label+' ')){let rest=clean(ls[i].slice(label.length).replace(/^\s*[:#-]?\s*/,''));if(rest&&rest.toLowerCase()!==label)return rest;for(let j=i+1;j<Math.min(i+3,ls.length);j++){if(ls[j])return ls[j]}}}}return''}
function mileageLabeled(){const ls=lines();for(let i=0;i<ls.length;i++){if(!/^(mileage|odometer)$/i.test(ls[i]))continue;for(let j=i+1;j<Math.min(i+4,ls.length);j++){const m=ls[j].match(/\b([0-9,]{1,8})\s*(miles?|mi\.?|kilometers?|km)\b/i);if(m)return mileage(m[0])}}const body=document.body?.innerText||'';const m=body.match(/(?:mileage|odometer)\s*[:\-]?\s*([0-9,]{1,8})\s*(miles?|mi\.?|kilometers?|km)\b/i);return m?mileage(m[0]):null}
function priceVisible(){let best=null;for(const el of document.querySelectorAll('body *')){if(el.children.length>4)continue;const t=clean(el.textContent);if(!/^\$\s*[0-9,]{3,7}(?:\.\d{2})?$/.test(t))continue;const n=number(t);if(n<500||n>1000000)continue;const ctx=clean(el.parentElement?.textContent||'').slice(0,220);let score=1;if(PRICE_GOOD.test(ctx))score+=5;if(PRICE_BAD.test(ctx))score-=8;if(/\b(\d{1,3})\s*(mi|miles)\b/i.test(ctx)&&!PRICE_GOOD.test(ctx))score-=2;if(!best||score>best.score||(score===best.score&&n<best.value))best={value:n,score}}return best}
function titleVehicle(){const h=clean(document.querySelector('h1')?.textContent||'');const title=h||clean(document.title);const y=year(title);if(!y)return{};let rest=clean(title.replace(new RegExp('^.*?'+y),'').replace(/^[-|: ]+/,'')).replace(/\s+/g,' ');const tokens=rest.split(' ').filter(Boolean);if(!tokens.length)return{year:y};let makeIndex=tokens.findIndex(x=>MAKES.has(x.toLowerCase()));if(makeIndex<0&&tokens.length>=2)makeIndex=0;if(makeIndex<0)return{year:y};const make=tokens[makeIndex];const remainder=tokens.slice(makeIndex+1);if(!remainder.length)return{year:y,make};const model=remainder.slice(0, Math.min(2,remainder.length)).join(' ');const trim=remainder.slice(Math.min(2,remainder.length)).join(' ');return{year:y,make,model,trim}}
function extract(){const data={},evidence={};const tv=titleVehicle();for(const[k,v]of Object.entries(tv))if(v){data[k]=v;evidence[k]='vehicle title'}const v=vin(labeled(['VIN','Vehicle Identification Number']));if(v){data.vin=v;evidence.vin='labeled text'}const s=labeled(['Stock Number','Stock #','Stock','Unit Number','Inventory #']);if(s&&!/^number$/i.test(s)){data.stock=s;evidence.stock='labeled text'}const m=mileageLabeled();if(m!=null){data.mileage=m;evidence.mileage='mileage label'}const p=priceVisible();if(p){data.price=p.value;evidence.price='visible currency price'}else{const lp=number(labeled(['Your Price','Our Price','Sale Price','Selling Price','Internet Price','Online Price','Cash Price',"Everyone's Price",'Everyone’s Price']));if(lp>=500&&lp<=1000000){data.price=lp;evidence.price='explicit price label'}}return{data,evidence,confidence:Object.fromEntries(Object.keys(data).map(k=>[k,evidence[k]==='visible currency price'?.78:.72]))}}window.CarBucketFallbackExtractor={extract}})();